packages:
  dht22: !include modules/dht22.yaml
  display: !include modules/display.yaml

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

psram:
  mode: quad
  speed: 80MHz

logger:

api:
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: led_ww
      - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop:

# --- I/O pins ---
i2c:
  sda: GPIO16
  scl: GPIO15
  scan: true
  frequency: 400kHz

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO8
    i2s_bclk_pin: GPIO2
  - id: i2s_speaker
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO11

switch:
  - platform: gpio
    pin: GPIO45
    id: led_ring_power
    restore_mode: ALWAYS_ON
    internal: true

  - platform: gpio
    pin: GPIO47
    id: speaker_amp_power
    restore_mode: ALWAYS_ON
    internal: true

  - platform: template
    id: mute
    name: Mute
    optimistic: true
    on_turn_on:
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: led_ww
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
    on_turn_off:
      - micro_wake_word.start:
      - light.turn_off: led_ww

binary_sensor:
  - platform: gpio
    id: center_button
    name: "Center Button"
    pin:
      number: GPIO1
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 20ms
    on_press:
      - voice_assistant.start:

button:
  - platform: restart
    name: "ESP32 Restart"
    id: but_rest

  - platform: template
    name: "Trigger Voice Assistant"
    icon: mdi:microphone
    on_press:
      - voice_assistant.start:

sensor:
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"
  - platform: wifi_signal
    name: "ESP32 WiFi Signal Strength"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    unit_of_measurement: "s"
light:
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: GRB
    pin: GPIO48
    rmt_symbols: 96
    num_leds: 1
    chipset: ws2812
    name: "Status LED"

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO4
    channel: left
    pdm: false
    i2s_audio_id: i2s_in
    bits_per_sample: 32 bit

speaker:
  - platform: i2s_audio
    id: va_speaker
    i2s_audio_id: i2s_speaker
    dac_type: external
    i2s_dout_pin: GPIO12
    channel: mono
    bits_per_sample: 32bit
    timeout: 500ms

# --- Voice Assistant ---
micro_wake_word:
  models:
    - model: github://esphome/micro-wake-word-models/models/v2/okay_nabu.json
    - model: github://esphome/micro-wake-word-models/models/v2/hey_jarvis.json
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
    - light.turn_on:
        id: led_ww
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%

voice_assistant:
  id: va
  microphone: va_mic
  speaker: va_speaker
  noise_suppression_level: 4.0
  volume_multiplier: 1.0
  conversation_timeout: 30s
  on_tts_start:
    - light.turn_on:
        id: led_ww
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%
    - lambda: id(voice_assistant_phase) = 4;
    - script.execute: draw_display
  on_listening:
    - lambda: id(voice_assistant_phase) = 2;
    - script.execute: draw_display
  on_stt_end:
    - lambda: id(voice_assistant_phase) = 3;
    - script.execute: draw_display
    - light.turn_off: led_ww
  on_error:
    - micro_wake_word.start:
  on_end:
    - light.turn_off: led_ww
    - wait_until:
        not:
          voice_assistant.is_running:
    - micro_wake_word.start:
    - lambda: id(voice_assistant_phase) = 1;
    - script.execute: draw_display

time:
  - platform: homeassistant
    id: esptime
