esphome:
  name: hall-9
  friendly_name: Hall 9 Room 1
    
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "990limTqrMH+hZO2Eg6kvbDyueKOd0y5IBtEpieOnCY="

ota:
  - platform: esphome
    password: "example"

wifi:
  ssid: "example"
  password: "12345678"
  output_power: 8.5dB
# Somehow helps to prevent crashes on wake word streaming start, Bug only mitigated when this is in local yaml not in remote package yaml (compiler related?)

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hall-9"
    password: "12345678"

captive_portal:

####

substitutions:
  tts_target: "example" # output speaker for external voice output

packages:
  hall_9: # This name can be anything
    url: https://github.com/chriopter/hall-9
    ref: main
    files: 
      - hall-9.yaml
#      - packages/radar_sensor.yaml
#      - packages/temperature_sensor.yaml
#      - packages/voice_assistant_alexa_output.yaml
    refresh: 0d