# Define Project Version
substitutions:
  project_version: "1.2.1"  # Define the version number once here, updated by release management

esphome:
  name: hall-9
  friendly_name: "Hall 9 Room 1"
  project:
    name: "chriopter.hall-9"
    version: "${project_version}"
# Automatic update check on startup
  on_boot:
    priority: 600  # Ensure this runs after the network is fully initialized
    then:
      - delay: 30s
      - button.press: check_updates

# Define text sensors for version tracking

globals:
  - id: latest_version_value
    type: std::string
    initial_value: ""  # Initially empty

text_sensor:
  - platform: template
    name: "Hall 9 Installed Version"
    id: current_version
    icon: "mdi:package-variant"
    update_interval: 24h
    lambda: |-
      return std::string("${project_version}");

  - platform: template
    name: "Hall 9 Latest Version"
    id: latest_version
    icon: "mdi:package-variant-closed"
    lambda: |-
      if (id(latest_version_value).empty()) {
        return { "Unknown" };
      } else {
        return { id(latest_version_value) };
      }
    update_interval: 24h

binary_sensor:
  - platform: template
    name: "Hall 9 Update Available"
    id: update_available
    device_class: update
    lambda: |-
      if (!id(latest_version).has_state()) return false;
      return id(latest_version).state != id(current_version).state;

# Define a button to manually check for updates

http_request:
  id: http_client
  useragent: esphome/hall-9
  timeout: 10s
  verify_ssl: true  # Enable SSL verification for security

button:
  - platform: template
    name: "Hall 9 Check for Updates"
    icon: "mdi:update"
    id: check_updates
    on_press:
      - http_request.get:
          id: http_client
          url: "https://api.github.com/repos/chriopter/hall-9/releases/latest"
          capture_response: true
          max_response_buffer_size: 10240
          on_response:
            then:
              - lambda: |-
                  // Parse the JSON response to extract the 'tag_name'
                  json::parse_json(body, [](JsonObject root) -> bool {
                    if (root.containsKey("tag_name")) {
                      const char* tag = root["tag_name"].as<const char*>();
                      id(latest_version_value) = tag;
                      ESP_LOGD("button", "Latest version: %s", tag);
                      return true;
                    } else {
                      ESP_LOGD("button", "No 'tag_name' found in the JSON response.");
                      return false;
                    }
                  });
              - logger.log:
                  format: "Update check completed."
                  level: DEBUG
              - text_sensor.template.publish:
                  id: latest_version
                  state: !lambda |-
                    return id(latest_version_value);
              - binary_sensor.template.publish:
                  id: update_available
                  state: !lambda |-
                    return id(latest_version_value) != id(current_version).state;
              - if:
                  condition:
                    lambda: |-
                      return id(latest_version_value) != id(current_version).state;
                  then:
                    - homeassistant.service:
                        service: notify_update
                        data:
                          message: !lambda |-
                            return "A new version (" + id(latest_version_value) + 
                                   ") is available for Hall 9.\n" +
                                   "Current version: " + id(current_version).state + "\n" +
                                   "Device: " + App.get_name() + "\n" +
                                   "IP: " + WiFi.get_ip_address().str();
          on_error:
            then:
              - logger.log:
                  format: "HTTP request failed!"
                  level: ERROR

# Automatic update check
interval:
  - interval: 6h
    then:
      - button.press: check_updates


